{
 "title": "Mc Tracker",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "SELECT\n  name || ' (' || type || ') - ' || asn_org || ' : ' || id AS display_name\nFROM (\n  SELECT\n    id,\n    name,\n    type,\n    asn_org,\n    ROW_NUMBER() OVER (\n      PARTITION BY id, name, type, asn_org\n      ORDER BY time DESC\n    ) AS rn\n  FROM ping\n  WHERE time >= NOW() - INTERVAL '7 days'\n    AND asn_org IN (${asn:sqlstring})\n) AS sub\nWHERE rn = 1;\n"
    }
   },
   {
    "name": "asn",
    "label": "ASN",
    "query": {
     "query": "SELECT\n  asn_org AS display_name\nFROM (\n  SELECT\n    asn_org,\n    ROW_NUMBER() OVER (\n      PARTITION BY asn_org\n      ORDER BY time DESC\n    ) AS rn\n  FROM ping\n  WHERE time >= NOW() - INTERVAL '7 days'\n    AND asn_org IS NOT NULL\n) AS sub\nWHERE rn = 1;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Seconds Ago" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  EXTRACT(EPOCH FROM (NOW() - MAX(time))) as seconds_since_last_update\r\nFROM ping;"
    }
   ]
  },
  {
   "title": "Players Online (now, per platform)",
   "type": "stat",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  SUM(CASE WHEN type = 'PC' THEN player_count ELSE 0 END) AS java,\r\n  SUM(CASE WHEN type = 'PE' THEN player_count ELSE 0 END) AS bedrock\r\nFROM (\r\n  SELECT\r\n    player_count,\r\n    type,\r\n    ROW_NUMBER() OVER (PARTITION BY id ORDER BY time DESC) AS rn\r\n  FROM ping\r\n) AS latest_per_server\r\nWHERE rn = 1;\r\n"
    }
   ]
  },
  {
   "title": "Players Online (now)",
   "type": "stat",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT SUM(player_count) AS total_players_now\r\nFROM (\r\n  SELECT player_count, ROW_NUMBER() OVER (PARTITION BY id ORDER BY time DESC) AS rn\r\n  FROM ping\r\n) AS latest_per_server\r\nWHERE rn = 1;\r\n"
    }
   ]
  },
  {
   "title": "Peak Players (Last 24h)",
   "type": "stat",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(total_players) AS peak_players_today\r\nFROM (\r\n  SELECT \r\n    bucket,\r\n    SUM(player_count) AS total_players\r\n  FROM (\r\n    SELECT DISTINCT ON (\r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00'),\r\n      id\r\n    )\r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n      id,\r\n      player_count\r\n    FROM ping\r\n    WHERE time >= DATE_TRUNC('day', NOW())\r\n      AND time <= NOW()\r\n    ORDER BY \r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00'),\r\n      id,\r\n      time DESC\r\n  ) AS latest_per_bucket\r\n  GROUP BY bucket\r\n) AS totals_per_bucket;"
    }
   ]
  },
  {
   "title": "Peak Players (Last Month)",
   "type": "stat",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT MAX(total_players) AS peak_players_this_month\r\nFROM (\r\n  SELECT \r\n    bucket,\r\n    SUM(player_count) AS total_players\r\n  FROM (\r\n    SELECT DISTINCT ON (\r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00'),\r\n      id\r\n    )\r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n      id,\r\n      player_count\r\n    FROM ping\r\n    WHERE time >= DATE_TRUNC('month', NOW())\r\n      AND time <= NOW()\r\n    ORDER BY\r\n      date_bin(INTERVAL '5 minutes', time, TIMESTAMP '1970-01-01 00:00:00'),\r\n      id,\r\n      time DESC\r\n  ) AS latest_per_bucket\r\n  GROUP BY bucket\r\n) AS totals_per_bucket;\r\n"
    }
   ]
  },
  {
   "title": "Tracked Servers",
   "type": "stat",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(*) AS total_servers\r\nFROM (\r\n  SELECT id, ROW_NUMBER() OVER (PARTITION BY id ORDER BY time DESC) AS rn\r\n  FROM ping\r\n) AS latest_per_server\r\nWHERE rn = 1;\r\n"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overall Player Count",
   "type": "timeseries",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH latest_per_bucket AS (\r\n    SELECT DISTINCT ON (\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), \r\n        id\r\n    )\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n        id,\r\n        player_count\r\n    FROM ping\r\n    WHERE time >= $__timeFrom\r\n      AND time <= $__timeTo\r\n    ORDER BY date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), id, time DESC\r\n)\r\nSELECT\r\n    bucket AS time,\r\n    SUM(player_count) AS total_players\r\nFROM latest_per_bucket\r\nGROUP BY bucket\r\nORDER BY bucket;"
    },
    {
     "dataset": "iox",
     "rawSql": "WITH latest_per_bucket AS (\r\n    SELECT DISTINCT ON (\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), \r\n        id\r\n    )\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n        id,\r\n        player_count\r\n    FROM ping\r\n    WHERE time >= $__timeFrom\r\n      AND time <= $__timeTo\r\n    ORDER BY date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), id, time DESC\r\n),\r\nbucket_totals AS (\r\n    SELECT\r\n        bucket,\r\n        SUM(player_count) AS total_players\r\n    FROM latest_per_bucket\r\n    GROUP BY bucket\r\n)\r\nSELECT\r\n    DATE_TRUNC('day', bucket) AS time,\r\n    MAX(total_players) AS daily_peak\r\nFROM bucket_totals\r\nGROUP BY DATE_TRUNC('day', bucket)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Per ASN Player Count (logarithmic)",
   "type": "timeseries",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH latest_per_bucket AS (\r\n    SELECT DISTINCT ON (\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), \r\n        id\r\n    )\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n        id,\r\n        asn_org,\r\n        player_count\r\n    FROM ping\r\n    WHERE time >= $__timeFrom\r\n      AND time <= $__timeTo\r\n    ORDER BY date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), id, time DESC\r\n)\r\nSELECT\r\n    bucket AS time,\r\n    asn_org,\r\n    SUM(player_count) AS total_players\r\nFROM latest_per_bucket\r\nGROUP BY bucket, asn_org\r\nORDER BY bucket, asn_org;\r\n"
    }
   ]
  },
  {
   "title": "Per Server Player Count (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS time,\r\n  name,\r\n  type,\r\n  AVG(player_count) AS player_count\r\nFROM ping\r\nWHERE time >= $__timeFrom\r\n  AND time <= $__timeTo\r\n  AND asn_org IN (${asn:sqlstring})\r\nGROUP BY time, name, type\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Per ASN Player Count (linear)",
   "type": "timeseries",
   "description": "Is not affected by ASN selection.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH latest_per_bucket AS (\r\n    SELECT DISTINCT ON (\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), \r\n        id\r\n    )\r\n        date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS bucket,\r\n        id,\r\n        asn_org,\r\n        player_count\r\n    FROM ping\r\n    WHERE time >= $__timeFrom\r\n      AND time <= $__timeTo\r\n    ORDER BY date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00'), id, time DESC\r\n)\r\nSELECT\r\n    bucket AS time,\r\n    asn_org,\r\n    SUM(player_count) AS total_players\r\nFROM latest_per_bucket\r\nGROUP BY bucket, asn_org\r\nORDER BY bucket, asn_org;\r\n"
    }
   ]
  },
  {
   "title": "Per Server Player Count (linear)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS time,\r\n  name,\r\n  type,\r\n  AVG(player_count) AS player_count\r\nFROM ping\r\nWHERE time >= $__timeFrom\r\n  AND time <= $__timeTo\r\n  AND asn_org IN (${asn:sqlstring})\r\nGROUP BY time, name, type\r\nORDER BY time;\r\n"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  date_bin($__interval, time, TIMESTAMP '1970-01-01 00:00:00') AS time,\r\n  name,\r\n  type,\r\n  AVG(player_count) AS player_count\r\nFROM ping\r\nWHERE id = '$server'\r\n  AND time >= $__timeFrom\r\n  AND time <= $__timeTo\r\nGROUP BY time, name, type\r\nORDER BY time;\r\n"
    }
   ]
  }
 ]
}