version: "3"

services:
  tracker:
    restart: always
    image: fascinated/mc-tracker:latest
    volumes:
      - ./data:/usr/src/app/data

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_SERVER_DOMAIN=mc-tracker.fascinated.cc
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influx/config:/etc/influxdb2
      - ./influx/db:/var/lib/influxdb2
