{
 "title": "Server Tracker",
 "description": "Minecraft server tracker. Shows current and past player counts.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "influx_bucket", "label": "Influx Bucket", "query": "mc-tracker" },
   {
    "name": "server",
    "label": "Server",
    "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> group()\r\n  |> distinct(column: \"name\")\r\n"
   },
   { "name": "global_interval", "label": "Global Interval", "query": "1h,6h,1d,7d" },
   { "name": "server_interval", "label": "Server Interval", "query": "1m,5m,10m,30m,1h,1d,7d" },
   {
    "name": "server_player_count_avg_interval",
    "label": "Player Count Avg Interval",
    "query": "1d,7d"
   }
  ]
 },
 "panels": [
  { "title": "Global Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "I created this tool to track the history of Minecraft servers, inspired by [Minetrack](https://github.com/Cryptkeeper/Minetrack). If you encounter any issues, please reach out to me on Discord using the username `fascinated7`.\n\nWant to add a server? You can do so by opening a pull request [here](https://git.fascinated.cc/Fascinated/mc-tracker/pulls) or messaging me on Discord.\n\nExplore additional metrics for the servers [here](https://mc-tracker.fascinated.cc/dashboards).\n\nIf you notice gaps in the metrics for a specific server, it means the server was offline during that time.\n"
   }
  },
  {
   "title": "Global Server Player Count (${global_interval} avg)",
   "type": "timeseries",
   "description": "When servers are offline (or don't respond) it can make the global count drop suddenly.",
   "gridPos": { "h": 10, "w": 14, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> aggregateWindow(every: ${global_interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> aggregateWindow(every: ${global_interval}, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"_measurement\"]) // Group by measurement to get a single result per measurement\r\n  |> aggregateWindow(every: ${global_interval}, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ _time: r._time, totalPlayerCombind: r._value })) // Retain time and rename the column\r\n  |> yield(name: \"totalPlayerCombind\")\r\n"
    }
   ]
  },
  {
   "title": "Total Players Online (now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value}))\r\n  |> group(columns: [])\r\n  |> sum()\r\n"
    }
   ]
  },
  {
   "title": "Total Tracked Servers",
   "type": "stat",
   "description": "The total count of tracked servers in the last month",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: -1mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> distinct(column: \"ip\")\r\n  |> group()\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Pings",
   "type": "stat",
   "description": "The total amount of times servers were pinged for their status",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> group(columns:[\"_measurement\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Last Server Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> group(columns: [\"_measurement\"]) // Group by server\r\n  |> last(column: \"_time\") // Get the latest timestamp for each server\r\n  |> group(columns: [\"_measurement\"]) // Group again to get each series\r\n  |> last() // Get the last value with that timestamp for each server\r\n"
    }
   ]
  },
  { "title": "Players Online Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "${server}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> last()\r\n"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Player Count (${server}, ${server_interval} avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> aggregateWindow(every: ${server_interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> aggregateWindow(every: ${server_player_count_avg_interval}, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({_time: r._time, \"1dayAvg\": r._value}))\r\n  |> yield(name: \"1dayAvg\")\r\n"
    },
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> map(fn: (r) => ({r with _value: r._value, _field: \"highestPlayerCount\"}))\r\n  |> max()"
    }
   ]
  },
  { "title": "Statistics for ${server}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 }, "repeat": "server" },
  {
   "title": "Player Count (${server_interval} avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> aggregateWindow(every: ${server_interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({_time: r._time, \"1dayAvg\": r._value}))\r\n  |> yield(name: \"1dayAvg\")\r\n"
    },
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> map(fn: (r) => ({r with _value: r._value, _field: \"highestPlayerCount\"}))\r\n  |> max()"
    }
   ]
  },
  {
   "title": "Latency/Ping (${server_interval} avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${influx_bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"playerCount\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${server}\")\r\n  |> aggregateWindow(every: ${server_interval}, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}