pub mod admin;
pub mod api;
pub mod auth;
pub mod chat;
pub mod chat_config;
pub mod chat_quota;
#[cfg(feature = "embedded-ui")]
pub mod embedded;
pub mod manager;
pub mod pinned_servers;
pub mod settings_api;
pub mod tracker_read;
